### ISSUE TITLE
obj model texture from mtl and png files.

### ISSUE THREAD

**Issue by mjhassan** [nicklockwood/GLView#26]
Hi,
Is there any way to load texture of a obj file from mtl and png files? Or convert mtl and png files into an image(png/jpg) file that supports GLView as texture?

I saw the issue #23, but it is not answered. Nick, would you please help us out?
Btw, thanks for updating the library.

**Comment by nicklockwood** [comment]
GLView doesn't load textures from an obj file, but it supports using a single texture per model, which can be loaded separately as a PNG file.

The Chair example in the GLModel Demo has a texture that is loaded in this way.

There are some restrictions on the texture image - it must has power-of-two dimensions, so you may need to resize and/or flip it vertically in photoshop before loading.

**Comment by mjhassan** [comment]
I saw the chair example, which loads texture from a tga file. The challenge is, I need to resize and/or flip texture image which, in my case, is quite difficult of adjust. The model and it's texture are auto generated from scanning and I'm not sure it has a size of power-of-two dimensions. I tried to load the texture from the .png file only, but it only shows some fragments of model texture and all green color. Obviously, that's because I don't know how to load .mtl file with that png as texture.
Anyway, I'm going to programmatically resize and flip the png and see if it loads the texture correctly.
Thanks for your quick reply. I'll let you know what I get from the experiment.

FYI, I got three files from scanning, a .obj file, a .mtl file and a .png file.

**Comment by mjhassan** [comment]
Well, good news is my png file is 1024x1024. Bad news is, the texture is still wrong even after I tried with both flipped and non-flipped version. The code I used to flip the image is,

     UIImage* flippedImage = [UIImage imageWithCGImage:imagePNG.CGImage
                                                    scale:imagePNG.scale
                                              orientation:UIImageOrientationUp];

and 

    UIImage* flippedImage = [UIImage imageWithCGImage:imagePNG.CGImage
                                                    scale:imagePNG.scale
                                              orientation:UIImageOrientationUpMirrored];

is there anything you can help guiding me with?

**Comment by nicklockwood** [comment]
Flipping the image using `UIImageOrientation` won't have any effect because it doesn't change the pixels. You can flip the image like this instead:

    UIGraphicsBeginImageContextWithOptions(imagePNG.size, NO, imagePNG.scale);
    GCContextRef context = UIGraphicsGetCurrentContext();
    CGContextDrawImage(context, (CGRect){{0, 0}, image.size}, image.CGImage);
    UIImage *flippedImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

**Comment by mjhassan** [comment]
First of all, thank you very much. I got the model exactly as it should be.

For anyone facing the same problem:
 * If you have jpg or png texture file forget about the mtl file to reduce confusion. GLView not dealing with that, for now :) .
 * Check if the image size is a size of power-of-two dimensions e.g. 512x512, 1024x1024 etc.
 * If not, write some code to adjust it programmatically.
 * Flip the image using Nick's code above.
 * Place the texture to GLView.

In summary:

        UIImage* imagePNG = [UIImage imageWithContentsOfFile:/*your_image_path*/];
        
        UIGraphicsBeginImageContextWithOptions(imagePNG.size, NO, imagePNG.scale);
        CGContextRef context = UIGraphicsGetCurrentContext();
        CGContextDrawImage(context, (CGRect){{0, 0}, imagePNG.size}, imagePNG.CGImage);
        UIImage *flippedImage = UIGraphicsGetImageFromCurrentImageContext();
        UIGraphicsEndImageContext();
        
        //set model
        modelView.texture = [GLImage imageWithUIImage:flippedImage];
        modelView.blendColor = nil;
        modelView.model = [GLModel modelWithContentsOfFile:/*your_obj_file_path*/];
